Use a virtualenv for robustness

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -8,7 +8,6 @@ test -n "$build_dir" -a -d "$build_dir" || exit
 cd $build_dir/../..
 
 export PYTHONHASHSEED=22
-VERSION=`git describe --tags`
 
 # Paramterize
 PYTHON_VERSION=3.6.4
@@ -70,28 +69,36 @@ PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install -s $PYTHON_VERSION && \
 pyenv global $PYTHON_VERSION || \
 fail "Unable to use Python $PYTHON_VERSION"
 
+rm -rf ./dist
+rm  -rf $BUILDDIR > /dev/null 2>&1
+mkdir $BUILDDIR
+
+info "Activating virtualenv $BUILDDIR/venv"
+python3 -m venv $BUILDDIR/venv
+source $BUILDDIR/venv/bin/activate
 
 info "Installing pyinstaller"
-python3 -m pip install pyinstaller -I --user || fail "Could not install pyinstaller"
+python3 -m pip install pyinstaller -I || fail "Could not install pyinstaller"
 
 info "Using these versions for building $PACKAGE:"
 sw_vers
 python3 --version
-echo -n "Pyinstaller "
-pyinstaller --version
 
-rm -rf ./dist
+info "Installing requirements..."
+python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt && \
+python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries.txt || \
+fail "Could not install requirements"
 
-
-rm  -rf $BUILDDIR > /dev/null 2>&1
-mkdir $BUILDDIR
+info "Installing hardware wallet requirements..."
+python3 -m pip install -Ir ./contrib/deterministic-build/requirements-hw.txt || \
+fail "Could not install hardware wallet requirements"
 
 info "Downloading icons..."
 for repo in icons; do
   git clone $GIT_REPO_ACCT/electrum-$repo $BUILDDIR/electrum-$repo
 done
 
-cp    $BUILDDIR/electrum-icons/icons_rc.py ./electrumsv/gui/qt/
+cp $BUILDDIR/electrum-icons/icons_rc.py ./electrumsv/gui/qt/
 
 info "Making locale..."
 ./contrib/make_locale || fail "Failed to make locale..."
@@ -123,19 +130,12 @@ xcodebuild || fail "Could not build CalinsQRReader"
 popd
 DoCodeSignMaybe "CalinsQRReader.app" "${d}/build/Release/CalinsQRReader.app" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
-info "Installing requirements..."
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt --user && \
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries.txt --user || \
-fail "Could not install requirements"
+info "Installing $PACKAGE..."
+python3 setup.py install > /dev/null || fail "Could not build $PACKAGE"
 
-info "Installing hardware wallet requirements..."
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements-hw.txt --user || \
-fail "Could not install hardware wallet requirements"
-
-info "Building $PACKAGE..."
-python3 setup.py install --user > /dev/null || fail "Could not build $PACKAGE"
-
-info "Building binary"
+VERSION=1.0.0
+PYINSTALLER_VERSION=$(pyinstaller --version)
+info "Using Pyinstaller version $PYINSTALLER_VERSION to build $PACKAGE version $VERSION"
 pyinstaller --noconfirm --ascii --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
 
 info "Adding bitcoincash URI types to Info.plist"
