...

diff --git a/.azure-pipelines/ci.yml b/.azure-pipelines/ci.yml
--- a/.azure-pipelines/ci.yml
+++ b/.azure-pipelines/ci.yml
@@ -15,9 +15,28 @@ pr:
   - master
 
 jobs:
+- job: ValidateCommit
+  pool:
+    vmImage: 'ubuntu-16.04'
+  steps:
+  - task: UsePythonVersion@0
+    inputs:
+      versionSpec: 3.6
+      addToPath: true
+      architecture: x64
+  - script: |
+      python3 -m pip install -U pylint
+      python3 -m pylint --rcfile .pylintrc electrum-sv electrumsv
+      if [ $? -gt 0 ]
+      then
+        # https://docs.pylint.org/en/1.6.0/run.html#exit-codes
+        echo "##vso[task.complete result=Failed;]DONE"
+      fi
 - job: Preparation
   pool:
     vmImage: 'ubuntu-16.04'
+  dependsOn:
+  - ValidateCommit
   steps:
   - script: |
       MOST_RECENT_TAG=`git describe --tags --abbrev=0 --match sv-*`
@@ -67,9 +86,6 @@ jobs:
       versionSpec: 3.6
       addToPath: true
       architecture: x64
-  - script: |
-      echo "$()"
-    displayName: 'Debug step'
   - script: |
       sudo docker pull $(imageName)
       sudo docker run --name electrumsv-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum --rm --workdir /opt/wine64/drive_c/electrum/contrib/build-wine $(imageName) ./build.sh
